# Generated by Django 5.0.2 on 2024-02-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_rename_username_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwords',
            old_name='password',
            new_name='created_password',
        ),
        migrations.RenameField(
            model_name='userspasswords',
            old_name='name_template',
            new_name='name_to_show',
        ),
        migrations.RenameField(
            model_name='userspasswords',
            old_name='password_template',
            new_name='password_to_show',
        ),
    ]
