# Generated by Django 5.0.2 on 2024-02-08 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_rename_password_passwords_created_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersPasswords',
        ),
    ]
