# Generated by Django 5.0.2 on 2024-02-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_profile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.AddField(
            model_name='passwords',
            name='password',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
    ]
